### ISSUE TITLE
KSL Search endpoint to get most recent car listings 

### ISSUE THREAD

**Issue by richardo2008** [DragonOfShuu/KSLHax#1]
Hey DragonOfShuu,

I love your repo and what you have done with it.

I am trying to get the ***most recent*** car listings from the search endpoint (as opposed to the searchByUrlParams endpoint).

Have you had any success hitting that other endpoint? I get authentication errors.

![image](https://github.com/DragonOfShuu/KSLHax/assets/15026226/d96a8459-2d4a-48e8-8e43-f5e5d71537e5)
![image](https://github.com/DragonOfShuu/KSLHax/assets/15026226/33921aea-ea54-46f3-9f17-4068d38e6f0f)

**Comment by DragonOfShuu** [comment]
# Getting Recent Cars

If you use `searchByUrlParams`, the first results it gives are actually going to be the most recent results. Looking through KSL's networking, I can see that if you do an empty search on KSL cars, KSL's frontend makes a call to the `searchByUrlParams` endpoint. For that reason, I don't see too much of a need to use another endpoint (does the `/search` endpoint even exist?).

# Getting Data From KSL

My program actually does not use `api3.ksl.com`. It looks like that endpoint requires authentication. My program actually makes the same API calls that their frontend makes to the backend. If you want more information on how that works, I recommend either looking through my code, or using the inspect tool on KSL cars when searching. 

If you would like to see directly how KSL Cars frontend makes API calls, first make an empty search in ksl cars with the networking tab open on the inspect tools. The call you are looking for will be under the name `proxy`. There are about 4 proxy calls, and it looks like KSL makes the call you are looking for some time after all the fonts have loaded in.

Good luck with your program! If this helped, go ahead and close this issue!

**Comment by richardo2008** [comment]
@DragonOfShuu - Thank you! This was really helpful. I was able to implement your suggestion.

One last question. Have you had any luck getting classifieds data back? I dont see "proxy" in the network call when looking in classifieds.

**Comment by DragonOfShuu** [comment]
Unfortunately for classifieds, it looks like the client doesn't receive straight JSON; instead it looks like that call is made on the server, and therefore server rendered. 

For that reason, I can't easily estimate how that endpoint is contacted. But, if you'd like, it might be possible to scrape the html that is sent to the client. The way the frontend arranges parameters is very simple:
```
https://classifieds.ksl.com/search/keyword/couch/zip/84003/miles/25
```

So, if you wanted to search for a couch it would be `/keyword/couch/`, and if you wanted your search to be within 25 miles it would be `/miles/25/`. I recommend making searches on KSL and looking at the URL for the `/KEY/VALUE/` pattern.

I also recommend setting your user agent to the one your browser uses so KSL doesn't stop your request, and then using a library that can go through the html.

Good luck!
